// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numberOfRuns = Integer.parseInt( args[0] ) ; 
		double countGreater = 0  ;
		double countEqualOrLess = 0;
		for (int i = 0; i < numberOfRuns; i++){
            double randomNumber = Math.random();
            if (randomNumber > 0.5) {
                countGreater++;
            } else {
                countEqualOrLess ++;
            }
        }
        System.out.println("> 0.5 : " + (int) countGreater);
        System.out.println("<= 0.5 : " + (int) countEqualOrLess);	
		if ( countEqualOrLess > 0 && countGreater  > 0 ) {
			double ratio = ( countGreater / countEqualOrLess ) ;
			System.out.println( " Ratio: " + ratio );
		} else {
			System.out.println("Ratio cannot be defined");
		}
	 }	 
   }

	
